"""Confidence scoring and transparency labels for Provenance Guard.

`confidence` is the combined estimate of P(text is AI), in [0, 1]:
    0.50 = maximum uncertainty (coin flip)
    ->1.0 = increasingly confident the text is AI
    ->0.0 = increasingly confident the text is human

See planning.md §2 and §3 for the full rationale.
"""

from __future__ import annotations

# Signal weights (see planning.md §2). LLM dominates because the statistical
# signals are the ones most likely to false-positive on formal human writing.
W_LLM = 0.50
W_STRUCTURAL = 0.25
W_LEXICAL = 0.25

# Asymmetric thresholds — deliberately reluctant to call something AI.
AI_THRESHOLD = 0.70
HUMAN_THRESHOLD = 0.30


def combine(llm: dict, structural: dict, lexical: dict) -> dict:
    """Combine the three signal dicts into a single calibrated confidence score.

    Returns {confidence, attribution, disagreement, weights, reliability}.
    """
    s_llm = llm["ai_likelihood"]
    s_struct = structural["ai_likelihood"]
    s_lex = lexical["ai_likelihood"]

    # Redistribute weight away from any unreliable statistical signal onto the LLM.
    w_llm, w_struct, w_lex = W_LLM, W_STRUCTURAL, W_LEXICAL
    if not structural["reliable"]:
        w_llm += w_struct
        w_struct = 0.0
    if not lexical["reliable"]:
        w_llm += w_lex
        w_lex = 0.0

    total_w = w_llm + w_struct + w_lex
    raw = (w_llm * s_llm + w_struct * s_struct + w_lex * s_lex) / total_w

    # Stylometry (statistical) view vs. LLM (semantic) view.
    stylo_parts = []
    if structural["reliable"]:
        stylo_parts.append(s_struct)
    if lexical["reliable"]:
        stylo_parts.append(s_lex)
    stylometry = sum(stylo_parts) / len(stylo_parts) if stylo_parts else s_llm

    # Disagreement penalty: pull toward 0.5 when semantic and statistical views diverge.
    disagreement = abs(s_llm - stylometry)
    confidence = raw - (raw - 0.5) * disagreement * 0.5

    # If the LLM signal itself failed (unreliable) and stats are thin, force uncertainty.
    if not llm["reliable"] and not structural["reliable"]:
        confidence = 0.5

    confidence = round(max(0.0, min(1.0, confidence)), 4)

    if confidence >= AI_THRESHOLD:
        attribution = "likely_ai"
    elif confidence <= HUMAN_THRESHOLD:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    return {
        "confidence": confidence,
        "attribution": attribution,
        "disagreement": round(disagreement, 4),
        "weights": {"llm": w_llm, "structural": w_struct, "lexical": w_lex},
        "reliability": {
            "llm": llm["reliable"],
            "structural": structural["reliable"],
            "lexical": lexical["reliable"],
        },
    }


def _directional_pct(confidence: float) -> int:
    """Percent phrased in the label's own direction.

    confidence 0.95 -> "95% likely AI"; confidence 0.05 -> "95% likely human".
    """
    if confidence >= 0.5:
        return round(confidence * 100)
    return round((1 - confidence) * 100)


def make_label(confidence: float) -> dict:
    """Map a confidence score to one of three transparency label variants.

    Returns {variant, headline, body, confidence_line, display}.
    """
    pct = _directional_pct(confidence)

    if confidence >= AI_THRESHOLD:
        variant = "high_confidence_ai"
        headline = "⚠ Likely AI-generated"
        body = (
            "Our analysis suggests this content was most likely produced with the help "
            "of a generative AI tool. This is an automated estimate, not a certainty."
        )
        confidence_line = (
            f"Confidence: {pct}% likely AI-generated. The creator can contest this result."
        )
    elif confidence <= HUMAN_THRESHOLD:
        variant = "high_confidence_human"
        headline = "✓ Likely human-written"
        body = (
            "Our analysis found no strong signals of AI generation — this reads as "
            "human-written. This is an automated estimate, not a guarantee of authorship."
        )
        confidence_line = f"Confidence: {pct}% likely human-written."
    else:
        variant = "uncertain"
        headline = "◑ Origin uncertain"
        body = (
            "Our analysis was inconclusive. We can't reliably tell whether this was "
            "written by a person or generated by AI, so we are not making a "
            "determination. Treat the origin as unknown."
        )
        confidence_line = "The creator can add context."

    return {
        "variant": variant,
        "headline": headline,
        "body": body,
        "confidence_line": confidence_line,
        "display": f"{headline}\n{body}\n{confidence_line}",
    }
