"""Detection signals for Provenance Guard.

Every signal returns the same shape:

    {
        "ai_likelihood": float in [0, 1],   # 1.0 = looks fully AI, 0.0 = fully human
        "reliable": bool,                    # False when the text is too short/degenerate
        "detail": {...},                     # human-readable breakdown for the audit log
    }

Three genuinely distinct signals (see planning.md §1):
  1. LLM classifier (Groq)      -> semantic / holistic coherence
  2. Structural stylometry      -> sentence-rhythm "burstiness"
  3. Lexical / register         -> vocabulary and formality
"""

from __future__ import annotations

import json
import os
import re
from statistics import mean, pstdev

from dotenv import load_dotenv

load_dotenv()

# --------------------------------------------------------------------------- #
# Shared tokenisation helpers
# --------------------------------------------------------------------------- #

_SENTENCE_SPLIT = re.compile(r"[.!?]+(?:\s|$)")
_WORD = re.compile(r"[A-Za-z']+")


def _sentences(text: str) -> list[str]:
    parts = [s.strip() for s in _SENTENCE_SPLIT.split(text)]
    return [s for s in parts if s]


def _words(text: str) -> list[str]:
    return _WORD.findall(text)


def _clamp(x: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, x))


# --------------------------------------------------------------------------- #
# Signal 1 — LLM classifier (Groq)
# --------------------------------------------------------------------------- #

LLM_MODEL = "llama-3.3-70b-versatile"

_LLM_SYSTEM = (
    "You are a forensic text analyst. Given a passage, estimate the probability that it "
    "was generated by an AI language model rather than written by a human. Consider "
    "holistic coherence, generic fluency, hedging, and voice — not just surface style. "
    "Be aware that highly formal or non-native human writing is often mistaken for AI; "
    "do not over-penalise formality alone. Respond ONLY with compact JSON of the form "
    '{"ai_probability": <float 0..1>, "reasoning": "<one sentence>"}.'
)


def llm_signal(text: str) -> dict:
    """Signal 1: ask Groq to judge whether the text reads as AI-generated.

    Falls back to a neutral, unreliable result if the API key is missing or the call
    fails, so the pipeline never crashes on an API hiccup.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return {
            "ai_likelihood": 0.5,
            "reliable": False,
            "detail": {"error": "GROQ_API_KEY not set; LLM signal unavailable"},
        }

    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model=LLM_MODEL,
            temperature=0.0,
            max_tokens=200,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _LLM_SYSTEM},
                {"role": "user", "content": text},
            ],
        )
        raw = resp.choices[0].message.content
        data = json.loads(raw)
        prob = _clamp(float(data.get("ai_probability", 0.5)))
        return {
            "ai_likelihood": round(prob, 4),
            "reliable": True,
            "detail": {
                "model": LLM_MODEL,
                "reasoning": str(data.get("reasoning", ""))[:300],
            },
        }
    except Exception as exc:  # network, parse, rate-limit, etc.
        return {
            "ai_likelihood": 0.5,
            "reliable": False,
            "detail": {"error": f"LLM signal failed: {exc.__class__.__name__}: {exc}"},
        }


# --------------------------------------------------------------------------- #
# Signal 2 — Structural stylometry (burstiness)
# --------------------------------------------------------------------------- #

# Human sentence-length variation (coefficient of variation) is typically high.
# CV >= this value reads as fully human; CV near 0 (uniform) reads as AI.
_CV_HUMAN_CEILING = 0.60


def structural_signal(text: str) -> dict:
    """Signal 2: sentence-length burstiness and uniformity.

    Low variance in sentence length -> more AI-like. Marked unreliable for very short
    texts where the statistic is meaningless (poetry, one-liners, lists).
    """
    sentences = _sentences(text)
    words = _words(text)
    lengths = [len(_words(s)) for s in sentences]
    lengths = [n for n in lengths if n > 0]

    if len(lengths) < 4 or len(words) < 25:
        return {
            "ai_likelihood": 0.5,
            "reliable": False,
            "detail": {
                "note": "too short for reliable structural analysis",
                "sentences": len(lengths),
                "words": len(words),
            },
        }

    mu = mean(lengths)
    sigma = pstdev(lengths)
    cv = sigma / mu if mu else 0.0

    # Burstiness: low CV -> AI (1.0), CV >= ceiling -> human (0.0).
    burstiness_ai = _clamp(1.0 - cv / _CV_HUMAN_CEILING)

    # Uniformity: fraction of sentences within +/-25% of the mean length. High -> AI.
    within = sum(1 for n in lengths if abs(n - mu) <= 0.25 * mu)
    uniformity = within / len(lengths)
    uniformity_ai = _clamp((uniformity - 0.4) / 0.5)  # 0.4->0, 0.9->1

    ai_likelihood = 0.6 * burstiness_ai + 0.4 * uniformity_ai

    return {
        "ai_likelihood": round(ai_likelihood, 4),
        "reliable": True,
        "detail": {
            "sentences": len(lengths),
            "mean_sentence_len": round(mu, 2),
            "sentence_len_cv": round(cv, 3),
            "uniformity": round(uniformity, 3),
            "burstiness_ai": round(burstiness_ai, 3),
            "uniformity_ai": round(uniformity_ai, 3),
        },
    }


# --------------------------------------------------------------------------- #
# Signal 3 — Lexical / register
# --------------------------------------------------------------------------- #

_CONTRACTION = re.compile(r"\b\w+'(?:t|re|s|ll|ve|m|d)\b", re.IGNORECASE)
_INFORMAL_WORDS = {
    "ok", "okay", "lol", "honestly", "kinda", "sorta", "gonna", "wanna",
    "yeah", "yep", "nope", "stuff", "kids", "guy", "guys", "cool", "awesome",
    "dunno", "gotta", "meh", "ugh", "vibe", "vibes",
}
_AI_TRANSITIONS = [
    "furthermore", "moreover", "additionally", "in conclusion",
    "it is important to note", "it is worth noting", "in today's world",
    "delve", "leverage", "paradigm", "underscore", "multifaceted",
    "in the realm of", "navigate the complexities", "tapestry",
    "ever-evolving", "landscape of",
]


def lexical_signal(text: str) -> dict:
    """Signal 3: register — informal markers (human) vs. AI-favoured connectives."""
    words = _words(text)
    if len(words) < 15:
        return {
            "ai_likelihood": 0.5,
            "reliable": False,
            "detail": {"note": "too short for reliable lexical analysis", "words": len(words)},
        }

    lower = text.lower()
    n = len(words)

    contractions = len(_CONTRACTION.findall(text))
    informal_hits = sum(1 for w in words if w.lower() in _INFORMAL_WORDS)
    # standalone lowercase "i" as a pronoun -> casual
    lowercase_i = len(re.findall(r"(?<![A-Za-z])i(?![A-Za-z'])", text))
    informal_total = contractions + informal_hits + lowercase_i
    informal_rate = informal_total / n

    ai_transition_hits = sum(lower.count(t) for t in _AI_TRANSITIONS)
    transition_rate = ai_transition_hits / n

    # More informality -> human (informal_rate >= 0.05 -> fully human).
    informality_ai = _clamp(1.0 - informal_rate / 0.05)
    # More AI-style transitions -> AI (rate >= 0.02 -> fully AI).
    transition_ai = _clamp(transition_rate / 0.02)

    ai_likelihood = 0.5 * informality_ai + 0.5 * transition_ai

    return {
        "ai_likelihood": round(ai_likelihood, 4),
        "reliable": True,
        "detail": {
            "informal_markers": informal_total,
            "informal_rate": round(informal_rate, 4),
            "ai_transition_hits": ai_transition_hits,
            "informality_ai": round(informality_ai, 3),
            "transition_ai": round(transition_ai, 3),
        },
    }
